### ISSUE TITLE
Still using `mio` pypi name?

### ISSUE THREAD

**Issue by sneakers-the-rat** [heuer/mio#1]
Hello! 

We are working on a project that has the abbreviation `mio` ( https://github.com/Aharoni-Lab/miniscope-io ) and we noticed that the pypi project only has one release in 2011. We were wondering if you would be willing to let us use that name? Making friendly contact with you first according to [PEP 541](https://peps.python.org/pep-0541/#how-to-request-a-name-transfer) :), don't want to try and request a transfer via pypi support if you were planning on still using it!

**Comment by heuer** [comment]
Please initiate a transfer, I'll ACK it

**Comment by sneakers-the-rat** [comment]
lovely :) 

I believe that the way to transfer ownership of a project is just to add me as an owner of the repository ( my username is the same: https://pypi.org/user/sneakers-the-rat/ ) , and then i can remove you ( https://discuss.python.org/t/transferring-a-pypi-name-to-someone-else/7196 ). 

It seems like "friendly name transfers" are not well documented ( https://discuss.python.org/t/pep-541-and-friendly-pypi-transfers/37776 ) and PEP 541 is mostly about abandoned projects where the maintainer is unresponsive, but i am also happy to raise an issue to announce the transfer if you'd prefer :)

**Comment by heuer** [comment]
I have to look at it this weekend or next week at the latest. 

I was hoping to just give my OK.

If you don't get a response, go on your way with the PEP mentioned.

**Comment by heuer** [comment]
This repository (Java, not Python), possibly also outdated, does not belong to the PyPI project, so I do not want to transfer the repository.

**Comment by sneakers-the-rat** [comment]
oh certainly not transferring the repository, just the pypi project name.

Should just be a matter of going here: https://pypi.org/manage/project/mio/collaboration/
and inviting me ( `sneakers-the-rat` ) as an owner :).

I also wish I could just give you a link to click/approve, but alas, it seems like this happens rarely enough that the process is a little awkward.
